consultores/consultores/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^(?P<filename>(humans.txt)|(robots.txt))$', views.home_files, name='home_files'),
    url(r'^', include('schema.urls', namespace="schema"))
]

consultores/schema/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.loginView, name='login'),
    url(r'^logout/$', views.logoutView, name='logout'),
    url(r'^authentication/$', views.loginAuthentication, name='loginAuthentication'),
    url(r'^home/$', views.home, name='home'),
    url(r'^nuevoCliente/$', views.nuevoClienteView, name='nuevoCliente'),
    url(r'^datosFacturacion/(?P<idCliente>[0-9]+)/$', views.datosFacturacionView, name='datosFacturacion'),
    url(r'^datosFacturacionAuth/(?P<idCliente>[0-9]+)/$', views.datosFacturacionAuth, name='datosFacturacionAuth'),
    url(r'^clientes/$', views.clientesView, name='clientes'),
    url(r'^clientes/(?P<idCliente>[0-9]+)/$', views.infoClienteView, name='infoCliente'),
    url(r'^seleccionCliente/(?P<context_type>[a-zA-Z]+)/$', views.seleccionClienteView, name='seleccionCliente'),
    url(r'^seleccionOrdenServicio/$', views.seleccionOrdenServicioView, name='seleccionOrdenServicio'),
    url(r'^nuevaComparativa/(?P<idCliente>[0-9]+)/$', views.nuevaComparativaView, name='nuevaComparativa'),
    url(r'^enviarCotizacionTramites/(?P<idComparativa>[0-9]+)/$', views.enviarCotizacionTramitesView, name='enviarCotizacionTramites'),
    url(r'^nuevaPoliza/(?P<idOrdenServicio>[0-9]+)/$', views.nuevaPolizaView, name='nuevaPoliza'),
    url(r'^nuevoPago/(?P<idPoliza>[0-9]+)/$', views.nuevoPagoView, name='nuevoPago'),
    url(r'^nuevoPagoAuth/(?P<idPoliza>[0-9]+)/$', views.nuevoPagoAuthView, name='nuevoPagoAuth'),
    url(r'^nuevaPolizaAuth/(?P<idOrdenServicio>[0-9]+)/$', views.nuevaPolizaAuthView, name='nuevaPolizaAuth'),
    url(r'^nuevaCotizacion/(?P<idComparativa>[0-9]+)/$', views.nuevaCotizacionView, name='nuevaCotizacion'),
    url(r'^nuevaComparativaAuth/(?P<idCliente>[0-9]+)/$', views.nuevaComparativaAuth, name='nuevaComparativaAuth'),
    url(r'^nuevaComparativaAPAuth/(?P<idCliente>[0-9]+)/$', views.nuevaComparativaAPAuth, name='nuevaComparativaAPAuth'),
    url(r'^nuevaCotizacionAuth/(?P<idComparativa>[0-9]+)/$', views.nuevaCotizacionAuth, name='nuevaCotizacionAuth'),
    url(r'^comparativas/$', views.comparativasView, name='comparativas'),
    url(r'^comparativas/(?P<idComparativa>[0-9]+)/$', views.comparativaClienteView, name='comparativaCliente'),
    url(r'^polizas/$', views.polizasView, name='polizas'),
    url(r'^polizas/(?P<idPoliza>[0-9]+)/$', views.polizaClienteView, name='polizaCliente'),
    url(r'^nuevoClienteAuth/$', views.nuevoClienteAuth, name='nuevoClienteAuthentication'),
    url(r'^cotizaciones/(?P<idCotizacion>[0-9]+)/$', views.cotizacionClienteView, name='cotizacionCliente'),
    url(r'^enviarComparativa/(?P<idComparativa>[0-9]+)/$', views.enviarComparativaView, name='enviarComparativa'),
    url(r'^marcarConcluida/(?P<idComparativa>[0-9]+)/$', views.marcarComparativaConcluidaView, name='marcarConcluida'),
    url(r'^marcarPreferida/(?P<idCotizacion>[0-9]+)/$', views.marcarCotizacionPreferidaView, name='marcarCotizacionPreferida'),
    url(r'^marcarComisionCobrada/(?P<idPoliza>[0-9]+)/$', views.marcarComisionCobradaView, name='marcarComisionCobrada'),
    url(r'^agentes/$', views.agentesView, name='agentes'),
    url(r'^agentes/(?P<idAgente>[0-9]+)/$', views.infoAgenteView, name='infoAgente'),
    url(r'^aseguradoras/$', views.aseguradorasView, name='aseguradoras'),
    url(r'^seguros/$', views.segurosView, name='seguros'),
    url(r'^eliminarCliente/(?P<idCliente>[0-9]+)/$', views.eliminarClienteView, name='eliminarCliente'),
    url(r'^eliminarComparativa/(?P<idComparativa>[0-9]+)/$', views.eliminarComparativaView, name='eliminarComparativa'),
]

consultores/schema/models.py
from django.db import models
from django.db.models import OneToOneField
from django.contrib.auth.models import User, Group

"""
 REVISAR IMPLEMENTACION DE URL PARA CADA CLASE
    #def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse()

http://stackoverflow.com/questions/12567151/how-to-add-column-in-manytomany-table-django
"""

SEGUROS_OPCIONES = (
    ('AP', 'Automóviles y pickups'),
    ('C', 'Camiones'),
    ('R', 'Remolques, cajas secas y adaptaciones en general'),
    ('G', 'Gastos médicos mayores'),
    ('V', 'Vida'),
    ('H', 'Hogares'),
    ('I', 'Inversión'),
    ('E', 'Empresas'),
    ('EC', 'Equipo de contratistas'),
    ('T', 'Transportes'),
    ('ESP', 'Especializados'),
)

# Create your models here.
class Persona(models.Model):
    email = models.EmailField(max_length=254, verbose_name='Email')
    edad = models.PositiveSmallIntegerField(null=True, verbose_name='Edad')
    SEXO_OPCIONES = (
        ('M', 'Mujer'),
        ('H', 'Hombre'),
    )
    sexo = models.CharField(max_length=1, choices=SEXO_OPCIONES, verbose_name='Sexo')
    rfc = models.CharField(max_length=13, blank=True, verbose_name='R.F.C.')
    telefonoLada = models.PositiveSmallIntegerField(null=True, verbose_name='Lada')
    telefono = models.PositiveIntegerField(null=True, verbose_name='Teléfono')
    calle = models.CharField(max_length=50, blank=True, verbose_name='Calle')
    numeroExt = models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Número Ext.')
    numeroInt = models.CharField(max_length=6,blank=True, null=True, verbose_name='Número Int.')
    colonia = models.CharField(max_length=40, blank=True, verbose_name='Colonia')
    ciudad = models.CharField(max_length=30, blank=True, verbose_name='Ciudad')
    estado = models.CharField(max_length=19, blank=True, verbose_name='Estado')
    codigoPostal = models.PositiveIntegerField(blank=True, null=True, verbose_name='C.P.')
    class Meta:
        abstract = True
    def __str__(self):
        return "Persona"

class Cliente(Persona):
    idCliente = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=40, verbose_name='Nombre')
    apellidoPaterno = models.CharField(max_length=30, verbose_name='Apellido Paterno')
    apellidoMaterno = models.CharField(max_length=30, verbose_name='Apellido Materno')
    linkRegistroRFC = models.URLField(blank=True, null=True, verbose_name='Registro R.F.C.')
    linkComprobanteDomicilio = models.FileField(null=True, verbose_name='Comprobante de Domicilio')
    calleFact = models.CharField(max_length=50, blank=True,null=True, verbose_name='Calle')
    numeroExtFact = models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Número Ext.')
    numeroIntFact = models.CharField(max_length=6, blank=True, null=True, verbose_name='Número Int.')
    coloniaFact = models.CharField(max_length=40, blank=True, null=True, verbose_name='Colonia')
    ciudadFact = models.CharField(max_length=30, blank=True, null=True, verbose_name='Ciudad')
    estadoFact = models.CharField(max_length=19, blank=True, null=True, verbose_name='Estado')
    codigoPostalFact = models.PositiveIntegerField(blank=True, null=True, verbose_name='C.P.')
    def __str__(self):
        return "Cliente fisico: " + self.nombre + " " +self.apellidoPaterno + " " + self.apellidoMaterno

#Creo que seria mejor agregar como campos dentro de Cliente
class ClienteFisico(Cliente):
    def __str__(self):
        return "Cliente fisico"

#Creo que seria mejor agregar como campos dentro de Cliente
class ClienteMoral(Cliente):
    razonSocial = models.CharField(max_length=100, null=True, verbose_name='Razón Social')
    linkActaConstitutiva = models.URLField(null=True, verbose_name='Acta Constitutiva')
    linkIdRepresentante = models.URLField(null=True, verbose_name='ID del Representante')
    def __str__(self):
        return "Cliente moral"

class Agente(Persona):
    userAgente = OneToOneField(User)
    claveAgente = models.IntegerField(blank=True, null=True, verbose_name='Clave de Agente')
    cuentaBancaria = models.CharField(max_length=34, blank=True, verbose_name='Cuenta Bancaria')
    banco = models.CharField(max_length=30, blank=True, verbose_name='Banco')
    clientes = models.ManyToManyField(Cliente, through='ClienteAgente')

    def save(self, *args, **kwargs):
        try:
            groupAgente = Group.objects.get(name='agente')
            self.userAgente.groups.add(groupAgente)
        except Group.DoesNotExist:
            groupAgente = Group.objects.create(name='agente')
            self.userAgente.groups.add(groupAgente)
        self.userAgente.groups.add(groupAgente)
        super(Agente, self).save(*args, **kwargs)

    def __str__(self):
        return "Agente: " + self.userAgente.username

class ClienteAgente(models.Model):
    cliente = models.ForeignKey(Cliente)
    agente = models.ForeignKey(Agente)
    fecha = models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')

class Administrador(Persona):
    userAdmin = OneToOneField(User)

    def save(self, *args, **kwargs):
        try:
            groupAdmin = Group.objects.get(name='admin')
            self.userAdmin.groups.add(groupAdmin)
        except Group.DoesNotExist:
            groupAdmin = Group.objects.create(name='admin')
            self.userAdmin.groups.add(groupAdmin)
        self.userAdmin.groups.add(groupAdmin)
        super(Administrador, self).save(*args, **kwargs)

    def __str__(self):
        return "Administrador: " + self.userAdmin.username

class TipoSeguro(models.Model):
    # tipo = models.CharField(max_length=3, choices=SEGUROS_OPCIONES, null=True)
    idTipoSeguro = models.AutoField(primary_key=True)
    nombre = models.ForeignKey('Seguro', null=True)
    def attrs(self):
        print("Not implemented")

class Aseguradora(models.Model):
    idAseguradora = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=50, verbose_name='Nombre')
    sitioWeb = models.URLField(blank=True, null=True, verbose_name='Sitio Web')
    telefonoLada = models.CharField(max_length=3, blank=True, verbose_name='Lada')
    telefono = models.CharField(max_length=7, blank=True, verbose_name='Teléfono')
    calle = models.CharField(max_length=50, blank=True, verbose_name='Calle')
    numeroExt = models.PositiveSmallIntegerField(blank=True, verbose_name='Número Ext.')
    numeroInt = models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Número Int.')
    colonia = models.CharField(max_length=40, blank=True, verbose_name='Colonia')
    ciudad = models.CharField(max_length=30, blank=True, verbose_name='Ciudad')
    estado = models.CharField(max_length=19, blank=True, verbose_name='Estado')
    codigoPostal = models.CharField(max_length=5, blank=True, verbose_name='C.P.')
    seguros = models.ManyToManyField(TipoSeguro)

    def __str__(self):
        return self.nombre

class Comparativa(models.Model):
    idComparativa = models.AutoField(primary_key=True)
    fechaCreacion = models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')
    fechaConclusion = models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Conclusión')
    fechaEnvioCliente = models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío a Cliente')
    fechaEnvioTramite = models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío a Trámites')
    tipoSeguro = models.ForeignKey('TipoSeguro')
    coberturas = models.ManyToManyField('Cobertura')
    cotizacionElegida = models.OneToOneField('Cotizacion', related_name='comparativaPreferida', null=True)

class Cotizacion(models.Model):
    idCotizacion = models.AutoField(primary_key=True)
    costo = models.DecimalField(max_digits=11, decimal_places=2, verbose_name='Costo')
    fechaCreacion = models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')
    FORMA_PAGO_OPCIONES = (
        (1, 'Anual'),
        (2, 'Semestral'),
        (4, 'Trimestral'),
        (12, 'Mensual'),
    )
    formaPago = models.IntegerField(choices=FORMA_PAGO_OPCIONES, default=12, verbose_name='Forma de Pago')
    comparativa = models.ForeignKey('Comparativa', null=True)
    aseguradora = models.ForeignKey('Aseguradora')
    archivo = models.FileField(null=True, blank=True, verbose_name='Archivo')
    elegida = models.BooleanField(default=False, verbose_name='Elegida')
    def __str__(self):
        return "Cotizacion: " + self.idCotizacion + " de comparativa: " + self.comparativa

class AreaTramites(models.Model):
    idAreaTramites = models.AutoField(primary_key=True)
    encargado = models.CharField(max_length=60, null=True, verbose_name='Nombre del Encargado')
    email = models.EmailField(null=True, verbose_name='Email')

class Poliza(models.Model):
    idPoliza = models.AutoField(primary_key=True)
    noPoliza = models.CharField(max_length=20, null=True, verbose_name='Número de póliza')
    primaNeta = models.DecimalField(max_digits=11, decimal_places=2, verbose_name='Prima Neta')
    fechaEmision = models.DateTimeField(verbose_name='Fecha de Emisión')
    fechaInicio = models.DateTimeField(verbose_name='Fecha de Inicio')
    fechaFin = models.DateTimeField(null=True, verbose_name='Fecha de Fin')
    endosoBeneficiario = models.CharField(max_length=100, blank=True, verbose_name='Nombre del Beneficiario Endosado')
    caratulaPDF = models.FileField(null=True, verbose_name='Carátula de Póliza')
    comision = models.OneToOneField('Comision', null=True)
    cotizacion = models.OneToOneField('Cotizacion', null=True)
    ordenServicio = models.OneToOneField('OrdenServicio', null=True)

class Pago(models.Model):
    idPago = models.AutoField(primary_key=True)
    cantidad = models.DecimalField(max_digits=11, decimal_places=2, verbose_name='Cantidad')
    fechaPago = models.DateTimeField(verbose_name='Fecha de Pago')
    numeroPago = models.PositiveSmallIntegerField(verbose_name='Número de Pago')

consultores/schema/forms.py
from django import forms
from django.forms import ModelForm
from .models import Agente, Cliente, Cotizacion, CoberturaUtilizada, Poliza, Pago, SeguroAP, SeguroC, SeguroR, SeguroG, SeguroV, SeguroH, SeguroI, SeguroE, SeguroEC, SeguroT

class LoginForm(forms.Form):
    user = forms.CharField(max_length=30)
    password = forms.CharField(max_length=30)

class nuevoClienteForm(forms.ModelForm):
	class Meta:
 		model = Cliente
 		fields = ['nombre','apellidoPaterno','apellidoMaterno','email','telefonoLada','telefono','edad','sexo','rfc','calle','numeroExt',
 		'numeroInt','colonia','ciudad','estado','codigoPostal','calleFact','numeroExtFact','numeroIntFact','coloniaFact','ciudadFact'
 		,'estadoFact','codigoPostalFact']


class CotizacionForm(forms.ModelForm):
    class Meta:
        model = Cotizacion
        fields = ['costo', 'formaPago', 'aseguradora', 'archivo']

class CoberturaUtilizadaForm(forms.ModelForm):
    class Meta:
        model = CoberturaUtilizada
        fields = ['idCobertura', 'sumaAsegurada', 'deducible']

class PolizaForm(forms.ModelForm):
    class Meta:
        model = Poliza
        fields = ['idPoliza', 'noPoliza', 'primaNeta', 'fechaEmision', 'fechaInicio', 'fechaFin', 'endosoBeneficiario', 'caratulaPDF']
        # fields = '__all__'

class PagoForm(forms.ModelForm):
    class Meta:
        model = Pago
        fields = ['idPago', 'cantidad', 'fechaPago', 'comprobante']

class UploadFileForm(forms.Form):
    # title = forms.CharField(max_length=50)
    file = forms.FileField()


# FORMAS DE SEGUROS
class SeguroAPForm(forms.ModelForm):
	class Meta:
		model = SeguroAP
		fields = ['tipoPlan', 'marca', 'modelo', 'ano', 'version', 'transmision', 'pasajeros', 'descripcion', 'descripcion']

class SeguroCForm(forms.ModelForm):
	class Meta:
		model = SeguroC
		fields = ['marca', 'modelo', 'ano', 'transmision', 'unidad', 'pasajeros', 'descripcion']

class SeguroRForm(forms.ModelForm):
    class Meta:
        model = SeguroR
        fields = ['capacidad', 'ejes', 'descripcion']

class SeguroGForm(forms.ModelForm):
    class Meta:
        model = SeguroG
        fields = ['nombreAsegurado', 'coaseguro', 'topeCoaseguro']

class SeguroVForm(forms.ModelForm):
    class Meta:
        model = SeguroV
        fields = ['nombreAsegurado', 'edad', 'sexo', 'fumador', 'link']

class SeguroHForm(forms.ModelForm):
    class Meta:
        model = SeguroH
        fields = ['tipoVivienda', 'metrosCuadrados', 'primeraResidencia', 'calle', 'numeroExt', 'numeroInt', 'colonia', 'ciudad', 'estado', 'codigoPostal', 'capitalContinente', 'capitalContenido']

class SeguroIForm(forms.ModelForm):
    class Meta:
        model = SeguroI
        fields = ['sumaAsegurada', 'planAhorro', 'identificacion']

class SeguroEForm(forms.ModelForm):
    class Meta:
        model = SeguroE
        fields = ['nombreEmpresa', 'tipoConstruccion', 'tipoMuro', 'numeroPisos', 'numeroSotanos', 'direccion', 'numeroExt',
        'numeroInt', 'colonia', 'ciudad', 'estado', 'codigoPostal']

class SeguroECForm(forms.ModelForm):
    class Meta:
        model = SeguroEC
        fields = ['tipoEquipo', 'caracteristicas']

class SeguroTForm(forms.ModelForm):
    class Meta:
        model = SeguroT
        fields = ['tipoTrabajo', 'tipoMedio', 'bienTransportado', 'sumaAsegurada', 'ciudadOrigen', 'estadoOrigen',
        'ciudadDestino', 'estadoDestino']

class EliminarClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = []

consultores/schema/templates/schema/comparativacliente.html
{% extends "base.html" %}

{% block head_title %}Cliente: {{ comparativa.cliente.nombre }} {{ cliente.apellidoPaterno }} {{ cliente.apellidoMaterno }}{% endblock %}
{% block head_css %}

<!-- DataTables CSS -->
<link rel="stylesheet" type="text/css" href="../../static/css/dataTables/dataTables.bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/css/jasny-bootstrap.min.css">

{% endblock %}
{% block head_javascript %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/js/jasny-bootstrap.min.js"></script>
{% endblock %}

{% block comparativas_tag %}class="active"{% endblock %}
{% block body_content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h4>Comparativa de
                {{ comparativa.ordenServicio.cliente.nombre }}
                {{ comparativa.ordenServicio.cliente.apellidoPaterno }}
                {{ comparativa.ordenServicio.cliente.apellidoMaterno }}
            </h4>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="pull-right" style="position: relative; top:.6em;">
                <a id="concluida" onclick="marcar_boton_concluida('{% url 'schema:marcarConcluida' comparativa.pk %}', this.id, 'envioCliente', 'envioTramite')" class="btn btn-default btn-sm btn-new-pos">
                    Marcar como concluida
                </a>
                                <!-- TODO: disable when no of cotizaciones is zero -->
                <a id="envioCliente" onclick="enviarCliente('{% url 'schema:enviarComparativa' comparativa.pk %}', this.id)" title="La comparativa podrá enviarse una vez haya sido concluida" class="btn btn-default btn-sm btn-new-pos">
                    Enviar comparativa a cliente
                </a>
                <a id="envioTramite" onclick="enviarTramites('{% url 'schema:enviarCotizacionTramites' comparativa.pk %}', this.id)" class="btn btn-default btn-sm btn-new-pos">
                    Enviar cotización preferida a trámites
                </a>
                <a href="#" class="btn btn-warning btn-sm">
                    <div class="glyphicon glyphicon-edit"></div>
                    Editar
                </a>
                <a href="{% url 'schema:eliminarComparativa' comparativa.pk %}" class="btn btn-danger btn-sm">
                    <div class="glyphicon glyphicon-trash"></div>
                    Eliminar
                </a>
            </div>
        </div>
    </div>
    <div class="row">
        <br>
        <div class="col-md-9">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-md-9">
                            <div class="panel-title">Cotizaciones de la comparativa</div>
                        </div>
                        <div class="col-md-3">
                        {% if comparativa.fechaConclusion == None %}
                            
                            <a id="nuevaCotizacion" href="{% url 'schema:nuevaCotizacion' comparativa.pk %}" class="pull-right btn btn-default btn-sm">
                                <div class="glyphicon glyphicon-plus"></div>
                                Nueva cotización
                            </a>
                        {% else %}
                            <a disabled href="#" class="pull-right btn btn-default btn-xs">Nueva cotización</a>
                        {% endif %}
                        </div>
                    </div>
                </div>
                <div class="panel-body">
                    <table class="table table-hover" id="cotizacionesTable">
                        <thead>
                            <tr>
                                <th>ID Cotización</th>
                                <th>Aseguradora</th>
                                <th>Costo</th>
                                <th>No. de coberturas</th>
                                <th>Forma de pago</th>
                                <th>Fecha de creación</th>
                            </tr>
                        </thead>
                        <tbody class="rowlink" data-link="row">
                        {% for cotizacion in comparativa.cotizacion_set.all %}
                            <tr id="comparativa{{ forloop.counter }}">
                                <td>
                                    <a href="{% url 'schema:cotizacionCliente' cotizacion.pk %}">{{ cotizacion.pk }}</a>
                                </td>
                                <td>
                                    {{ cotizacion.aseguradora.nombre }}
                                </td>
                                <td>
                                    {{ cotizacion.costo }}
                                </td>
                                <td>
                                    {{ cotizacion.coberturautilizada_set.all.count }}
                                </td>
                                <td>
                                    {{ cotizacion.get_formaPago_display }}
                                </td>
                                <td>
                                    {{ cotizacion.fechaCreacion }}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="row">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <div class="panel-title">Información del seguro a contratar</div>
                    </div>
                    <div class="panel-body">
                        <h4 class="list-group-item-heading">Datos</h4>
                        {% for field in datos %}
                            <strong>{{ field.label }}:</strong>
                            {% if field.data == None or field.data == '' %}
                                No especificado
                            {% else %}
                                {{ field.data }}
                            {% endif %}
                        <br>
                        {% endfor %}
                        <br>
                        <h4 class="list-group-item-heading">Coberturas deseadas</h4>
                        {% for cobertura in comparativa.coberturas.all %}
                                <li>
                                    {{ cobertura.nombre }}
                                </li>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <div class="panel-title">
                            <a href="{% url 'schema:infoCliente' comparativa.ordenServicio.cliente.pk %}">
                                Información del cliente
                            </a>
                        </div>
                    </div>
                    <div class="panel-body">
                        <p>
                            <strong>Nombre:</strong>
                            {{ comparativa.ordenServicio.cliente.nombre }}
                            {{ comparativa.ordenServicio.cliente.apellidoPaterno }}
                            {{ comparativa.ordenServicio.cliente.apellidoMaterno }}
                        </p>
                        <p>
                            <strong>Correo:</strong>
                            {% if comparativa.ordenServicio.cliente.email %}
                                {{ comparativa.ordenServicio.cliente.email }}
                            {% else %}
                                N/A
                            {% endif %}
                        </p>
                        <p>
                            <strong>Teléfono:</strong>
                            {% if cliente.telefono %}
                                ({{ cliente.telefonoLada }}) {{ cliente.telefono }}
                            {% else %}
                                N/A
                            {% endif %}
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block footer_javascript %}
<!-- ajax -->
<script src="/static/js/ajax/marcar_botones.js"></script>
<script>
    window.onload = function() {
        console.log("function on load");
        init_disabled_marking('{{ comparativa.fechaConclusion }}', 'concluida', 'envioCliente', 'envioTramite', 'nuevaCotizacion');
    }
</script>
<!-- jQuery -->

<!-- DataTables -->
<script type="text/javascript" charset="utf8" src="../../static/js/dataTables/jquery.dataTables.min.js"></script>
<script type="text/javascript" charset="utf8" src="../../static/js/dataTables/dataTables.bootstrap.min.js"></script>
<script>
$(document).ready( function () {
    $('#cotizacionesTable').DataTable();
} );
</script>
{% endblock %}

consultores/schema/templates/schema/nuevaPoliza.html
{% extends "base.html" %}
{% block head_title %}Nuevo Póliza{% endblock %}
{% block head_css %}

    <link rel="stylesheet" href="../../static/css/custom/styles_nuevocliente.css">
    <script type = "text/javascript" src = "../../static/js/custom/datosClientes.js"></script>

    <!-- <link rel="stylesheet" href="http://bootswatch.com/paper/bootstrap.css"> -->
{% endblock %}


{% block body_content %}
<!-- check out the following: https://docs.djangoproject.com/en/dev/howto/custom-template-tags/ -->


<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3>Nueva póliza</h3>
            <form enctype="multipart/form-data" action="{% url 'schema:nuevaPolizaAuth' orden.pk %}" method="post">
                {% csrf_token %}
                {{ polizaForm.as_p }}
                <div class="form-group">
                    <div class="col-lg-10 col-lg-offset-2">
                        <input type="reset" name ="cancelar" class="nuevoClientemodal-submit" value="Cancelar">
                        <input type="submit" name="crear" class=" nuevoClientemodal-submit" value="Crear">
                    </div>
                </div>
            </form>

            {% if error_missingfields %}<p class="red-color">{{ error_missingfields }}</p>{% endif %}
            {% if error_wrongpassword %}<p class="red-color">{{ error_wrongpassword }}</p>{% endif %}
        </div>
    </div>
</div>


{% endblock %}