consultores/consultores/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^(?P<filename>(humans.txt)|(robots.txt))$', views.home_files, name='home_files'),
    url(r'^', include('schema.urls', namespace="schema"))
]

consultores/schema/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.loginView, name='login'),
    url(r'^logout/$', views.logoutView, name='logout'),
    url(r'^authentication/$', views.loginAuthentication, name='loginAuthentication'),
    url(r'^home/$', views.home, name='home'),
    url(r'^nuevoCliente/$', views.nuevoClienteView, name='nuevoCliente'),
    url(r'^datosFacturacion/(?P<idCliente>[0-9]+)/$', views.datosFacturacionView, name='datosFacturacion'),
    url(r'^datosFacturacionAuth/(?P<idCliente>[0-9]+)/$', views.datosFacturacionAuth, name='datosFacturacionAuth'),
    url(r'^clientes/$', views.clientesView, name='clientes'),
    url(r'^clientes/(?P<idCliente>[0-9]+)/$', views.infoClienteView, name='infoCliente'),
    url(r'^seleccionCliente/(?P<context_type>[a-zA-Z]+)/$', views.seleccionClienteView, name='seleccionCliente'),
    url(r'^seleccionOrdenServicio/$', views.seleccionOrdenServicioView, name='seleccionOrdenServicio'),
    url(r'^nuevaComparativa/(?P<idCliente>[0-9]+)/$', views.nuevaComparativaView, name='nuevaComparativa'),
    url(r'^enviarCotizacionTramites/(?P<idComparativa>[0-9]+)/$', views.enviarCotizacionTramitesView, name='enviarCotizacionTramites'),
    url(r'^nuevaPoliza/(?P<idOrdenServicio>[0-9]+)/$', views.nuevaPolizaView, name='nuevaPoliza'),
    url(r'^nuevoPago/(?P<idPoliza>[0-9]+)/$', views.nuevoPagoView, name='nuevoPago'),
    url(r'^nuevoPagoAuth/(?P<idPoliza>[0-9]+)/$', views.nuevoPagoAuthView, name='nuevoPagoAuth'),
    url(r'^nuevaPolizaAuth/(?P<idOrdenServicio>[0-9]+)/$', views.nuevaPolizaAuthView, name='nuevaPolizaAuth'),
    url(r'^nuevaCotizacion/(?P<idComparativa>[0-9]+)/$', views.nuevaCotizacionView, name='nuevaCotizacion'),
    url(r'^nuevaComparativaAuth/(?P<idCliente>[0-9]+)/$', views.nuevaComparativaAuth, name='nuevaComparativaAuth'),
    url(r'^nuevaComparativaAPAuth/(?P<idCliente>[0-9]+)/$', views.nuevaComparativaAPAuth, name='nuevaComparativaAPAuth'),
    url(r'^nuevaCotizacionAuth/(?P<idComparativa>[0-9]+)/$', views.nuevaCotizacionAuth, name='nuevaCotizacionAuth'),
    url(r'^comparativas/$', views.comparativasView, name='comparativas'),
    url(r'^comparativas/(?P<idComparativa>[0-9]+)/$', views.comparativaClienteView, name='comparativaCliente'),
    url(r'^polizas/$', views.polizasView, name='polizas'),
    url(r'^polizas/(?P<idPoliza>[0-9]+)/$', views.polizaClienteView, name='polizaCliente'),
    url(r'^nuevoClienteAuth/$', views.nuevoClienteAuth, name='nuevoClienteAuthentication'),
    url(r'^cotizaciones/(?P<idCotizacion>[0-9]+)/$', views.cotizacionClienteView, name='cotizacionCliente'),
    url(r'^enviarComparativa/(?P<idComparativa>[0-9]+)/$', views.enviarComparativaView, name='enviarComparativa'),
    url(r'^marcarConcluida/(?P<idComparativa>[0-9]+)/$', views.marcarComparativaConcluidaView, name='marcarConcluida'),
    url(r'^marcarPreferida/(?P<idCotizacion>[0-9]+)/$', views.marcarCotizacionPreferidaView, name='marcarCotizacionPreferida'),
    url(r'^marcarComisionCobrada/(?P<idPoliza>[0-9]+)/$', views.marcarComisionCobradaView, name='marcarComisionCobrada'),
    url(r'^agentes/$', views.agentesView, name='agentes'),
    url(r'^agentes/(?P<idAgente>[0-9]+)/$', views.infoAgenteView, name='infoAgente'),
    url(r'^aseguradoras/$', views.aseguradorasView, name='aseguradoras'),
    url(r'^seguros/$', views.segurosView, name='seguros'),
    url(r'^eliminarCliente/(?P<idCliente>[0-9]+)/$', views.eliminarClienteView, name='eliminarCliente'),
    url(r'^eliminarComparativa/(?P<idComparativa>[0-9]+)/$', views.eliminarComparativaView, name='eliminarComparativa'),
]

consultores/schema/forms.py
from django import forms
from django.forms import ModelForm
from .models import Agente, Cliente, Cotizacion, CoberturaUtilizada, Poliza, Pago, SeguroAP, SeguroC, SeguroR, SeguroG, SeguroV, SeguroH, SeguroI, SeguroE, SeguroEC, SeguroT

class LoginForm(forms.Form):
    user = forms.CharField(max_length=30)
    password = forms.CharField(max_length=30)

class nuevoClienteForm(forms.ModelForm):
	class Meta:
 		model = Cliente
 		fields = ['nombre','apellidoPaterno','apellidoMaterno','email','telefonoLada','telefono','edad','sexo','rfc','calle','numeroExt',
 		'numeroInt','colonia','ciudad','estado','codigoPostal','calleFact','numeroExtFact','numeroIntFact','coloniaFact','ciudadFact'
 		,'estadoFact','codigoPostalFact']


class CotizacionForm(forms.ModelForm):
    class Meta:
        model = Cotizacion
        fields = ['costo', 'formaPago', 'aseguradora', 'archivo']

class CoberturaUtilizadaForm(forms.ModelForm):
    class Meta:
        model = CoberturaUtilizada
        fields = ['idCobertura', 'sumaAsegurada', 'deducible']

class PolizaForm(forms.ModelForm):
    class Meta:
        model = Poliza
        fields = ['idPoliza', 'noPoliza', 'primaNeta', 'fechaEmision', 'fechaInicio', 'fechaFin', 'endosoBeneficiario', 'caratulaPDF']
        # fields = '__all__'

class PagoForm(forms.ModelForm):
    class Meta:
        model = Pago
        fields = ['idPago', 'cantidad', 'fechaPago', 'comprobante']

class UploadFileForm(forms.Form):
    # title = forms.CharField(max_length=50)
    file = forms.FileField()


# FORMAS DE SEGUROS
class SeguroAPForm(forms.ModelForm):
	class Meta:
		model = SeguroAP
		fields = ['tipoPlan', 'marca', 'modelo', 'ano', 'version', 'transmision', 'pasajeros', 'descripcion', 'descripcion']

class SeguroCForm(forms.ModelForm):
	class Meta:
		model = SeguroC
		fields = ['marca', 'modelo', 'ano', 'transmision', 'unidad', 'pasajeros', 'descripcion']

class SeguroRForm(forms.ModelForm):
    class Meta:
        model = SeguroR
        fields = ['capacidad', 'ejes', 'descripcion']

class SeguroGForm(forms.ModelForm):
    class Meta:
        model = SeguroG
        fields = ['nombreAsegurado', 'coaseguro', 'topeCoaseguro']

class SeguroVForm(forms.ModelForm):
    class Meta:
        model = SeguroV
        fields = ['nombreAsegurado', 'edad', 'sexo', 'fumador', 'link']

class SeguroHForm(forms.ModelForm):
    class Meta:
        model = SeguroH
        fields = ['tipoVivienda', 'metrosCuadrados', 'primeraResidencia', 'calle', 'numeroExt', 'numeroInt', 'colonia', 'ciudad', 'estado', 'codigoPostal', 'capitalContinente', 'capitalContenido']

class SeguroIForm(forms.ModelForm):
    class Meta:
        model = SeguroI
        fields = ['sumaAsegurada', 'planAhorro', 'identificacion']

class SeguroEForm(forms.ModelForm):
    class Meta:
        model = SeguroE
        fields = ['nombreEmpresa', 'tipoConstruccion', 'tipoMuro', 'numeroPisos', 'numeroSotanos', 'direccion', 'numeroExt',
        'numeroInt', 'colonia', 'ciudad', 'estado', 'codigoPostal']

class SeguroECForm(forms.ModelForm):
    class Meta:
        model = SeguroEC
        fields = ['tipoEquipo', 'caracteristicas']

class SeguroTForm(forms.ModelForm):
    class Meta:
        model = SeguroT
        fields = ['tipoTrabajo', 'tipoMedio', 'bienTransportado', 'sumaAsegurada', 'ciudadOrigen', 'estadoOrigen',
        'ciudadDestino', 'estadoDestino']

class EliminarClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = []

consultores/schema/views.py
from django.shortcuts import render, render_to_response
from . import forms
from django.forms import formset_factory
from django.forms import BaseFormSet
from schema import models
from .models import Agente, Administrador, Cliente, ClienteFisico, ClienteMoral, ClienteAgente, AsignacionComision, Comision, Poliza, Pago, Seguro, AreaTramites, TipoSeguro, OrdenServicio, Comparativa, Aseguradora, Contacto, Cobertura, Cotizacion, CoberturaUtilizada
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_protect
from django.contrib import messages
# from easy_pdf.views import PDFTemplateView
from . import managers
from django.forms.models import model_to_dict
from django.core.mail import send_mail, EmailMessage, EmailMultiAlternatives
from datetime import datetime, timedelta
from django.template import loader
# Create your views here.

# from django.conf.settings import PROJECT_ROOT

# HELPER FUNCTIONS
def getUser(username):
    try:
        user = User.objects.get(username=username)
        return user
    except User.DoesNotExist:
        return None

def isAgente(user):
    return user.groups.filter(name='agente').exists()

def whichUser(user):
    groupID = 0;
    if user.groups.filter(name="admin").exists():
        groupID = 2
    elif user.groups.filter(name='agente').exists():
        groupID = 1
    return groupID

# VIEWS
@csrf_protect
def loginView(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('schema:home'))
    else:
        context = {}
        return render(request, "schema/login.html", context)

@csrf_protect
def logoutView(request):
    logout(request)
    context = {'message_logoutsuccess': "¡Has salido exitosamente!"}
    return render(request, "schema/login.html", context)

@csrf_protect
def loginAuthentication(request):
    if request.method == "POST":
        login_form = forms.LoginForm(request.POST)
        if login_form.is_valid():
            user_form = login_form.cleaned_data['user']
            password_form = login_form.cleaned_data['password']
            user = authenticate(username=user_form, password=password_form)
            if user is not None:
                if user.is_active:
                    # request.session['username'] = user.username
                    login(request, user)
                    return HttpResponseRedirect(reverse('schema:home'))
                else:
                    context = {'error_sessionexpired': 'Sesión expirada'}
                    return render(request, 'schema/login.html', context)
            else:
                context = {'error_wrongpassword': "Usuario o contraseña incorrectos"}
                return render(request, 'schema/login.html', context)
        else:
            context = {'error_missingfields': "Campos sin llenar"}
            return render(request, 'schema/login.html', context)

#HACE FALTA IMPLEMENTAR
@login_required(redirect_field_name='')
def registerAgente(request):
    if whichUser(request.user) == 1:
        return HttpResponse("No autorizado")
    elif whichUser(request.user) == 2:
        return HttpResponse("Work in Progress")

@login_required(redirect_field_name='')
def home(request):
    if whichUser(request.user) == 1:
        agente = Agente.objects.get(userAgente=request.user)
        ordenes = agente.ordenservicio_set.all()
        meses = 2
        lastTwoMonths = datetime.today() - timedelta(days=meses*30)
        clienteReciente = None
        try:
            clienteReciente = agente.clientes.all().order_by('-pk')[0]
        except Exception as e:
            print(e)
        # filter polizas vencidas and activas
        polizasVencidas = Poliza.objects.filter(ordenServicio__agente=agente, fechaFin__lt=datetime.now())
        polizasActivas = Poliza.objects.filter(ordenServicio__agente=agente, fechaFin__gte=datetime.now())
        polizasSinCobrar = Poliza.objects.filter(ordenServicio__agente=agente, comision__fechaDeposito=None)
        # filter polizas from the last two months
        # polizas = Poliza.objects.filter(ordenServicio__agente=agente)
        polizas = Poliza.objects.filter(ordenServicio__agente=agente, fechaFin__gte=lastTwoMonths)
        cotizacionesSinPoliza = Cotizacion.objects.filter(comparativa__ordenServicio__agente=agente, elegida=True, poliza=None).exclude(comparativa__fechaEnvioTramite=None)
        comparativasPendientes = Comparativa.objects.filter(ordenServicio__agente=agente, fechaConclusion=None)
        for poliza in polizas:
            print(poliza)
        context = {
            'agente': agente,
            'ordenes': ordenes,
            'polizas': polizas,
            'polizasVencidas': polizasVencidas,
            'polizasActivas': polizasActivas,
            'polizasSinCobrar': polizasSinCobrar,
            'clienteReciente': clienteReciente,
            'comparativasPendientes': comparativasPendientes,
            'cotizacionesSinPoliza': cotizacionesSinPoliza,
            'meses': meses,
        }
        return render(request, 'schema/home.html', context)
    elif whichUser(request.user) == 2:
        context = {'agente': Administrador.objects.get(userAdmin=request.user)}
        return render(request, 'schema/homeAdmin.html', context)

@login_required(redirect_field_name='')
def nuevoClienteView(request):
    if whichUser(request.user) == 1:
        context = {'cliente': request.user.agente.clientes}
        return render(request, "schema/nuevoCliente.html", context)
    elif whichUser(request.user) == 2:
        return HttpResponse("No autorizado")

@login_required(redirect_field_name='')
def nuevoClienteAuth(request):
    if whichUser(request.user) == 1:
        if request.method == "POST":
            datos_form = forms.nuevoClienteForm(request.POST)
            if datos_form.is_valid():
                C = datos_form.save()
                CA = ClienteAgente(cliente=C, agente=request.user.agente)
                CA.save()
                return HttpResponseRedirect(reverse('schema:clientes'))
            else:
                context = {
                    'datos_form': datos_form,
                    'error_missingfields': "Campo obligatorio sin llenar",
                    'error_lada': "Campo obligatorio, ingresa unicamente numeros",
                    'error_telefono': "Campo obligatorio, ingresa unicamente numeros",
                    'error_email':"Campo obligatorio, ingresa un email valido",
                    'error_NE':"Ingresa unicamente numeros",
                    'error_CP':"Ingresa unicamente numeros"}
                return render(request, 'schema/nuevoCliente.html', context)
    elif whichUser(request.user) == 2:
        return HttpResponse("No autorizado")

@login_required(redirect_field_name='')
def datosFacturacionView(request, idCliente):
    if whichUser(request.user) == 1:
        context = {'cliente': Cliente.objects.get(pk=idCliente)}
        return render(request, 'schema/datosFacturacion.html', context)
    elif whichUser(request.user) == 2:
        return HttpResponse("No autorizado")

@login_required(redirect_field_name='')
def datosFacturacionAuth(request, idCliente):
    if whichUser(request.user) == 1:
        if request.method == "POST":
            facturacion_form = forms.nuevoClienteForm(request.POST)
            if facturacion_form.is_valid():
#             context = {'cliente': request.user.agente.clientes.get(pk=idCliente),}
                cliente = Cliente.objects.get(pk=idCliente)
                facturacion_form=forms.nuevoClienteForm(request.POST, instance = cliente)
                facturacion_form.save()
                context = {'cliente': cliente}
                return render(request, 'schema/infocliente.html', context)
            else:
                cliente = Cliente.objects.get(pk=idCliente)
                context = {
                    'cliente': cliente,
                    'error_missingfields': "Campos sin llenar"}
                return render(request, 'schema/datosFacturacion.html', context)
    elif whichUser(request.user) == 2:
        return HttpResponse("No autorizado")

@login_required(redirect_field_name='')
def clientesView(request):
    if whichUser(request.user) == 1:
        context = {'clientes': request.user.agente.clientes}
        return render(request, 'schema/clientes.html', context)
    elif whichUser(request.user) == 2:
        context = {'clienteagente': ClienteAgente.objects.all()}
        return render(request, 'schema/clientesAdmin.html', context)

@login_required(redirect_field_name='')
def infoClienteView(request, idCliente):
    if whichUser(request.user) == 1:
        context = {'cliente': Cliente.objects.get(pk=idCliente)}
        return render(request, 'schema/infocliente.html', context)
    elif whichUser(request.user) == 2:
        context = {
            'cliente': Cliente.objects.get(pk=idCliente),
            'relacionAgente': ClienteAgente.objects.get(cliente=idCliente)
        }
        return render(request, 'schema/infoclienteAdmin.html', context)

@login_required(redirect_field_name='')
def preNuevaComparativaView(request):
    if whichUser(request.user) == 1:
        context = {'clientes': request.user.agente.clientes}
        return render(request, 'schema/preNuevaComparativa.html', context)
    elif whichUser(request.user) == 2:
        return HttpResponse("No autorizado")

@login_required(redirect_field_name='')
def seleccionClienteView(request, context_type):
    context = {
        'clientes': request.user.agente.clientes,
        'context_type': context_type,
    }
    return render(request, 'schema/seleccionCliente.html', context)

@login_required(redirect_field_name='')
def enviarCotizacionTramitesView(request, idComparativa):

consultores/schema/templates/base.html
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>
            {% block head_title %}{% endblock %}
        </title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="apple-touch-icon" href="apple-touch-icon.png">

        <!-- <link rel="stylesheet" href="../static/css/bootstrap.min.css"> -->
        <link rel="stylesheet" href="https://bootswatch.com/paper/bootstrap.min.css">
        <style>
            body {
                padding-top: 50px;
                padding-bottom: 20px;
        </style>

        <!-- <link rel="stylesheet" href="../static/css/bootstrap-theme.min.css"> -->

        <link rel="stylesheet" href="/static/css/main.css">
        <link rel="stylesheet" href="/static/css/custom/navbarstyles.css">

        <script src="/static/js/vendor/modernizr-2.8.3-respond-1.4.2.min.js"></script>

        <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
        <script src="http://netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>

        {% block head_css %}{% endblock %}
        {% block head_javascript %}{% endblock %}

    </head>
    <body>
        <!-- navigation bar -->
        {% block navbar %}
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="">
                        <img src="/static/img/logo/logo.png" class="logo-size">
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li id="home" {% block home_tag %}{% endblock %}><a href="{% url 'schema:home' %}">Inicio</a></li>
                        <li id="clientes" {% block clientes_tag %}{% endblock %}><a href="{% url 'schema:clientes' %}">Clientes<span class="sr-only">(current)</span></a></li>
                        <li id="comparativas" {% block comparativas_tag %}{% endblock %}><a href="{% url 'schema:comparativas' %}">Comparativas</a></li>
                        <li id="polizas" {% block polizas_tag %}{% endblock %}><a href="{% url 'schema:polizas' %}">Pólizas</a></li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        <li><a>Agente {{ request.user.first_name }} {{ request.user.last_name }}</a></li>
                        <li><a href="{% url 'schema:logout' %}"><span class="glyphicon glyphicon-off" aria-hidden="true"></span> Salir</a></li>
                </div>
            </div>
        </nav>
        {% endblock %}
        <!-- end navigation bar -->

        <!-- THE BODY OF THE OTHER PAGES IS DISPLAYED HERE -->
        {% block body_content %} {% endblock %}



      <footer>
          <div class="base_footer">
              <p>&copy; Consultores Patrimoniales 2015</p>
          </div>
      </footer>
    </div> <!-- /container -->        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.11.2.min.js"><\/script>')</script>

        <script src="/static/js/vendor/bootstrap.min.js"></script>
        <script src="/static/js/main.js"></script>

        {% block footer_javascript %}{% endblock %} <!-- in case we want to add a js at the footer -->

        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        <script>
            (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
            function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
            e=o.createElement(i);r=o.getElementsByTagName(i)[0];
            e.src='//www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
            ga('create','UA-XXXXX-X','auto');ga('send','pageview');
        </script>
    </body>
</html>

consultores/schema/templates/baseAdmin.html
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>
            {% block head_title %}{% endblock %}
        </title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="apple-touch-icon" href="apple-touch-icon.png">

        <!-- <link rel="stylesheet" href="../static/css/bootstrap.min.css"> -->
        <link rel="stylesheet" href="https://bootswatch.com/paper/bootstrap.min.css">
        <style>
            body {
                padding-top: 50px;
                padding-bottom: 20px;
            }
        </style>

        <!-- <link rel="stylesheet" href="../static/css/bootstrap-theme.min.css"> -->

        <link rel="stylesheet" href="/static/css/mainAdmin.css">
        <link rel="stylesheet" href="/static/css/custom/navbarstyles_admin.css">

        <script src="/static/js/vendor/modernizr-2.8.3-respond-1.4.2.min.js"></script>

        <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
        <script src="http://netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>

        {% block head_css %}{% endblock %}
        {% block head_javascript %}{% endblock %}

    </head>
    <body>
        <!-- navigation bar -->
        {% block navbar %}
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand">
                        <img src="/static/img/logo/logo.png" class="logo-size">
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li id="home" {% block home_tag %}{% endblock %}><a href="{% url 'schema:home' %}">Inicio</a></li>
                        <li id="clientes" {% block clientes_tag %}{% endblock %}><a href="{% url 'schema:clientes' %}">Clientes<span class="sr-only">(current)</span></a></li>
                        <li id="comparativas" {% block comparativas_tag %}{% endblock %}><a href="{% url 'schema:comparativas' %}">Comparativas</a></li>
                        <li id="polizas" {% block polizas_tag %}{% endblock %}><a href="{% url 'schema:polizas' %}">Pólizas</a></li>
                        <li id="agentes" {% block agentes_tag %}{% endblock %}><a href="{% url 'schema:agentes' %}">Agentes<span class="sr-only">(current)</span></a></li>
                        <li id="aseguradoras" {% block aseguradoras_tag %}{% endblock %}><a href="{% url 'schema:aseguradoras' %}">Aseguradoras</a></li>
                        <li id="seguros" {% block seguros_tag %}{% endblock %}><a href="{% url 'schema:seguros' %}">Seguros</a></li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        <li><a>Administrador {{ request.user.first_name }} {{ request.user.last_name }}</a></li>
                        <li><a href="{% url 'schema:logout' %}"><span class="glyphicon glyphicon-off" aria-hidden="true"></span> Salir</a></li>
                </div>
            </div>
        </nav>
        {% endblock %}
        <!-- end navigation bar -->

        <!-- THE BODY OF THE OTHER PAGES IS DISPLAYED HERE -->
        {% block body_content %} {% endblock %}



      <footer>
          <div class="base_footer">
              <p>&copy; Consultores Patrimoniales 2015</p>
          </div>
      </footer>
    </div> <!-- /container -->        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.11.2.min.js"><\/script>')</script>

        <script src="/static/js/vendor/bootstrap.min.js"></script>
        <script src="/static/js/main.js"></script>

        {% block footer_javascript %}{% endblock %} <!-- in case we want to add a js at the footer -->

        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        <script>
            (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
            function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
            e=o.createElement(i);r=o.getElementsByTagName(i)[0];
            e.src='//www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
            ga('create','UA-XXXXX-X','auto');ga('send','pageview');
        </script>
    </body>
</html>

consultores/schema/templates/hello.html
{% extends "easy_pdf/base.html" %}

{% block content %}
    <div id="content">
        <h1>Hello</h1>
    </div>
{% endblock %}